### ISSUE TITLE
Production build doesn't work

### ISSUE THREAD

**Issue by kennethlarsen** [ember-learn/upgrade-guide#20]
`ember s -e production` does not work when visiting `localhost:4200`.

**Comment by kennethlarsen** [comment]
@abhilashlr Do you want to look into this?

**Comment by abhilashlr** [comment]
Yeah sure I can 😆

**Comment by abhilashlr** [comment]
@kennethlarsen From my initial findings, I couldn't find what is causing the issue, but I did an ember-cli-update to the repo itself and upgraded to Ember-3.18.0, and things seem to run. However, the styles are broken. I'll have a PR work done on this over the weekend.

**Comment by kennethlarsen** [comment]
@abhilashlr Awesome, thanks! Might need to update the ember-styleguide as well.

**Comment by abhilashlr** [comment]
`ember-styleguide` > "4.0.0-13" seems to break the UI of the app which I guess is due to https://github.com/ember-learn/ember-styleguide/compare/v4.0.0-13...v4.0.0-14#diff-168726dbe96b3ce427e7fedce31bb0bc. This is something we need to figure out as a separate task I believe - What do you suggest? I've upgraded ember to 3.18 and it's dependencies for this app in this PR #21.
